module SmartHomeModule

{
  interface LivingRoom
  {
    string getLightStatus();
    string turnLightsOn();
    string turnLightsOff();
    string lockDoor();
    string unlockDoor();
  };

   interface Kitchen
   {
    string getLightStatus();
    void lockDoor();
    void unlockDoor();
    void setTemp();
    string getTemp();  	
   };

 interface Outdoors
   {
    string getGardenLightStatus();
    void setLightStatus(); 
    void lockDoor();
    void unlockDoor();
    void openGate();
    string closeGate();     
   };

   interface Bathroom {
    string turnImmersionOn();
    string turnImmersionOff();
    string turnFanOn();
    string turnFanOff();
   };
};
