module SmartHomeModule

{
  interface LivingRoom
  {
    string getLightStatus();
    string turnLightsOn();
    string turnLightsOff();
    string lockDoor();
    string unlockDoor();
  };

   interface Kitchen
   {
    string turnBoilerOn();
    string turnBoierOff();
    string turnHeatingOn();
    string turnHeatingOff();
    
   };

 interface Outdoors
   {
    string turnOnOutDoorLights();
    string turnOffOutDoorLights(); 
    string lockGate();
    string unlockGate();

   };

   interface Bathroom {
    string turnImmersionOn();
    string turnImmersionOff();
    string turnFanOn();
    string turnFanOff();
   };
};
