package SmartHome;


/**
* SmartHome/_TwoImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 01 April 2017 12:00:06 o'clock IST
*/

public abstract class _TwoImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements SmartHome.Two, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _TwoImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("test", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SmartHome/Two/test
       {
         this.test ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SmartHome/Two:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _TwoImplBase
