package SmartHome;

/**
* SmartHome/LivingRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 01 April 2017 12:00:45 o'clock IST
*/

public final class LivingRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public SmartHome.LivingRoom value = null;

  public LivingRoomHolder ()
  {
  }

  public LivingRoomHolder (SmartHome.LivingRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SmartHome.LivingRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SmartHome.LivingRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SmartHome.LivingRoomHelper.type ();
  }

}
