package SmartHome;

/**
* SmartHome/TwoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 01 April 2017 12:00:06 o'clock IST
*/

public final class TwoHolder implements org.omg.CORBA.portable.Streamable
{
  public SmartHome.Two value = null;

  public TwoHolder ()
  {
  }

  public TwoHolder (SmartHome.Two initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SmartHome.TwoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SmartHome.TwoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SmartHome.TwoHelper.type ();
  }

}
