package SmartHome;


/**
* SmartHome/TwoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 01 April 2017 12:00:06 o'clock IST
*/

public interface TwoOperations 
{
  void test ();
} // interface TwoOperations
