package SmartHomeModule;


/**
* SmartHomeModule/_BathroomImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 23 April 2017 15:26:26 o'clock IST
*/

public abstract class _BathroomImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements SmartHomeModule.Bathroom, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _BathroomImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("turnImmersionOn", new java.lang.Integer (0));
    _methods.put ("turnImmersionOff", new java.lang.Integer (1));
    _methods.put ("turnFanOn", new java.lang.Integer (2));
    _methods.put ("turnFanOff", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SmartHomeModule/Bathroom/turnImmersionOn
       {
         String $result = null;
         $result = this.turnImmersionOn ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // SmartHomeModule/Bathroom/turnImmersionOff
       {
         String $result = null;
         $result = this.turnImmersionOff ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // SmartHomeModule/Bathroom/turnFanOn
       {
         String $result = null;
         $result = this.turnFanOn ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // SmartHomeModule/Bathroom/turnFanOff
       {
         String $result = null;
         $result = this.turnFanOff ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SmartHomeModule/Bathroom:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _BathroomImplBase
