package SmartHomeModule;


/**
* SmartHomeModule/_LivingRoomImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 16 April 2017 13:25:22 o'clock IST
*/

public abstract class _LivingRoomImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements SmartHomeModule.LivingRoom, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _LivingRoomImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getLightStatus", new java.lang.Integer (0));
    _methods.put ("turnLightsOn", new java.lang.Integer (1));
    _methods.put ("turnLightsOff", new java.lang.Integer (2));
    _methods.put ("lockDoor", new java.lang.Integer (3));
    _methods.put ("unlockDoor", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SmartHomeModule/LivingRoom/getLightStatus
       {
         String $result = null;
         $result = this.getLightStatus ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // SmartHomeModule/LivingRoom/turnLightsOn
       {
         String $result = null;
         $result = this.turnLightsOn ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // SmartHomeModule/LivingRoom/turnLightsOff
       {
         String $result = null;
         $result = this.turnLightsOff ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // SmartHomeModule/LivingRoom/lockDoor
       {
         String $result = null;
         $result = this.lockDoor ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // SmartHomeModule/LivingRoom/unlockDoor
       {
         String $result = null;
         $result = this.unlockDoor ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SmartHomeModule/LivingRoom:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _LivingRoomImplBase
