package SmartHomeModule;


/**
* SmartHomeModule/_OutdoorsImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 23 April 2017 15:26:26 o'clock IST
*/

public abstract class _OutdoorsImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements SmartHomeModule.Outdoors, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _OutdoorsImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getGardenLightStatus", new java.lang.Integer (0));
    _methods.put ("setLightStatus", new java.lang.Integer (1));
    _methods.put ("lockDoor", new java.lang.Integer (2));
    _methods.put ("unlockDoor", new java.lang.Integer (3));
    _methods.put ("openGate", new java.lang.Integer (4));
    _methods.put ("closeGate", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SmartHomeModule/Outdoors/getGardenLightStatus
       {
         String $result = null;
         $result = this.getGardenLightStatus ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // SmartHomeModule/Outdoors/setLightStatus
       {
         this.setLightStatus ();
         out = $rh.createReply();
         break;
       }

       case 2:  // SmartHomeModule/Outdoors/lockDoor
       {
         this.lockDoor ();
         out = $rh.createReply();
         break;
       }

       case 3:  // SmartHomeModule/Outdoors/unlockDoor
       {
         this.unlockDoor ();
         out = $rh.createReply();
         break;
       }

       case 4:  // SmartHomeModule/Outdoors/openGate
       {
         this.openGate ();
         out = $rh.createReply();
         break;
       }

       case 5:  // SmartHomeModule/Outdoors/closeGate
       {
         String $result = null;
         $result = this.closeGate ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SmartHomeModule/Outdoors:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _OutdoorsImplBase
