package SmartHomeModule;


/**
* SmartHomeModule/_OutdoorsImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 23 April 2017 22:27:29 o'clock IST
*/

public abstract class _OutdoorsImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements SmartHomeModule.Outdoors, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _OutdoorsImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("turnOnOutDoorLights", new java.lang.Integer (0));
    _methods.put ("turnOffOutDoorLights", new java.lang.Integer (1));
    _methods.put ("lockGate", new java.lang.Integer (2));
    _methods.put ("unlockGate", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SmartHomeModule/Outdoors/turnOnOutDoorLights
       {
         String $result = null;
         $result = this.turnOnOutDoorLights ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // SmartHomeModule/Outdoors/turnOffOutDoorLights
       {
         String $result = null;
         $result = this.turnOffOutDoorLights ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // SmartHomeModule/Outdoors/lockGate
       {
         String $result = null;
         $result = this.lockGate ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // SmartHomeModule/Outdoors/unlockGate
       {
         String $result = null;
         $result = this.unlockGate ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SmartHomeModule/Outdoors:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _OutdoorsImplBase
