package SmartHomeModule;


/**
* SmartHomeModule/BathroomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 22 April 2017 12:00:58 o'clock IST
*/

public interface BathroomOperations 
{
  String turnImmersionOn ();
  String turnImmersionOff ();
  String turnFanOn ();
  String turnFanOff ();
} // interface BathroomOperations
