package SmartHomeModule;

/**
* SmartHomeModule/BathroomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 22 April 2017 12:00:58 o'clock IST
*/

public final class BathroomHolder implements org.omg.CORBA.portable.Streamable
{
  public SmartHomeModule.Bathroom value = null;

  public BathroomHolder ()
  {
  }

  public BathroomHolder (SmartHomeModule.Bathroom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SmartHomeModule.BathroomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SmartHomeModule.BathroomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SmartHomeModule.BathroomHelper.type ();
  }

}
