package SmartHomeModule;


/**
* SmartHomeModule/KitchenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 23 April 2017 15:26:26 o'clock IST
*/

public interface KitchenOperations 
{
  String turnBoilerOn ();
  String turnBoierOff ();
  String turnHeatingOn ();
  String turnHeatingOff ();
} // interface KitchenOperations
