package SmartHomeModule;

/**
* SmartHomeModule/LivingRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 22 April 2017 12:00:58 o'clock IST
*/

public final class LivingRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public SmartHomeModule.LivingRoom value = null;

  public LivingRoomHolder ()
  {
  }

  public LivingRoomHolder (SmartHomeModule.LivingRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SmartHomeModule.LivingRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SmartHomeModule.LivingRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SmartHomeModule.LivingRoomHelper.type ();
  }

}
