package SmartHomeModule;


/**
* SmartHomeModule/LivingRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 16 April 2017 12:23:47 o'clock IST
*/

public interface LivingRoomOperations 
{
  String getLightStatus ();
  void lockDoor ();
  void unlockDoor ();
} // interface LivingRoomOperations
