package SmartHomeModule;


/**
* SmartHomeModule/LivingRoomOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 23 April 2017 22:27:29 o'clock IST
*/

public interface LivingRoomOperations 
{
  String getLightStatus ();
  String turnLightsOn ();
  String turnLightsOff ();
  String lockDoor ();
  String unlockDoor ();
} // interface LivingRoomOperations
