package SmartHomeModule;


/**
* SmartHomeModule/LivingRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SmartHome.idl
* 23 April 2017 22:27:29 o'clock IST
*/

public interface LivingRoom extends LivingRoomOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LivingRoom
